{% set name = "slcl1butils" %}
{% set version = "2025.3.10" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slcl1butils-{{ version }}.tar.gz
  sha256: 668517e11428b03226b6c204f853de5787de3fdb789227549c2653818a8c6a22

build:
  entry_points:
    - do_IW_L1C_SAFE_from_L1B_SAFE = slcl1butils.scripts.do_IW_L1C_SAFE_from_L1B_SAFE:main
    - do_WV_L1C_SAFE_from_L1B_SAFE = slcl1butils.scripts.do_WV_L1C_SAFE_from_L1B_SAFE:main
    - stack_WV_L1C_to_ZARR = slcl1butils.compute.stack_wv_l1c_monthly:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=2024.11.0
    - dask
    - numpy
    - netcdf4
    - shapely
    - scipy
    - matplotlib-base
    - tqdm
    - zarr
    - fsspec
    - aiohttp
    - PyYAML
    - holoviews
    - geoviews
    - pyogrio

test:
  imports:
    - slcl1butils
  commands:
    - pip check
    - do_IW_L1C_SAFE_from_L1B_SAFE --help
    - do_WV_L1C_SAFE_from_L1B_SAFE --help
    - stack_WV_L1C_to_ZARR --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/umr-lops/utils_xsarslc_l1b
  summary: Python library to exploit SAR IFREMER L1B products
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    python tool to read/display/enrich Sentinel-1 SAR Level-1 B SLC products produced at IFREMER

extra:
  recipe-maintainers:
    - agrouaze
    - alxmouche
