{% set name = "slcl1butils" %}
{% set version = "2024.7.2.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slcl1butils-{{ version }}.tar.gz
  sha256: e6195bae8b3a5f81906e63d930a3462634f928636facc7856508583b3836d400

build:
  entry_points:
    - do_IW_L1C_SAFE_from_L1B_SAFE = slcl1butils.scripts.do_IW_L1C_SAFE_from_L1B_SAFE:main
    - do_WV_L1C_SAFE_from_L1B_SAFE = slcl1butils.scripts.do_WV_L1C_SAFE_from_L1B_SAFE:main
    - stack_WV_L1C_to_ZARR = slcl1butils.compute.stack_wv_l1c_monthly:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - xarray
    - dask
    - numpy
    - netcdf4
    - shapely
    - scipy
    - matplotlib-base
    - xarray-datatree
    - tqdm
    - zarr
    - fsspec
    - aiohttp
    - PyYAML
    - holoviews
    - geoviews

test:
  imports:
    - slcl1butils
  commands:
    - pip check
    - do_IW_L1C_SAFE_from_L1B_SAFE --help
    - do_WV_L1C_SAFE_from_L1B_SAFE --help
    - stack_WV_L1C_to_ZARR --help
  requires:
    - pip

about:
  home: https://github.com/umr-lops/utils_xsarslc_l1b
  summary: Python library to exploit SAR IFREMER L1B products
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    python tool to read/display/enrich Sentinel-1 SAR Level-1 B SLC products produced at IFREMER

extra:
  recipe-maintainers:
    - agrouaze
    - alxmouche
